# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          BUILD_ONLY: true
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
